site_name: Polydev
nav:
  - Home: index.md
  - Installation: installation.md
  - Setup: setup.md
  - Language Specific Docs:
    - Java: languages/java.md
    - C: languages/c.md
    - Cpp: languages/cpp.md
    - Lua: languages/lua.md
    - Python: languages/python.md
theme:
  name: dracula
  language: en

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/DarthMooMancer

copyright: |
  &copy; 2025 <a href="https://github.com/DarthMooMancer" target="_blank" rel="noopener">DarthMooMancer</a>
